/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public.forgot-password'
import { Route as AppVehiclesRouteImport } from './routes/_app.vehicles'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppFuelRouteImport } from './routes/_app.fuel'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDriversRouteImport } from './routes/_app.drivers'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAiCopilotRouteImport } from './routes/_app.ai-copilot'
import { Route as AppVehiclesIndexRouteImport } from './routes/_app.vehicles.index'
import { Route as AppTripsIndexRouteImport } from './routes/_app.trips.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppMaintenanceIndexRouteImport } from './routes/_app.maintenance.index'
import { Route as AppFuelIndexRouteImport } from './routes/_app.fuel.index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app.expenses.index'
import { Route as AppDriversIndexRouteImport } from './routes/_app.drivers.index'
import { Route as AppVehiclesNewRouteImport } from './routes/_app.vehicles.new'
import { Route as AppVehiclesVehicleIdRouteImport } from './routes/_app.vehicles.$vehicleId'
import { Route as AppTripsNewRouteImport } from './routes/_app.trips.new'
import { Route as AppTripsHistoryRouteImport } from './routes/_app.trips.history'
import { Route as AppTripsTripIdRouteImport } from './routes/_app.trips.$tripId'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app.settings.preferences'
import { Route as AppSettingsAccountRouteImport } from './routes/_app.settings.account'
import { Route as AppReportsRoiRouteImport } from './routes/_app.reports.roi'
import { Route as AppReportsFuelRouteImport } from './routes/_app.reports.fuel'
import { Route as AppReportsFleetRouteImport } from './routes/_app.reports.fleet'
import { Route as AppReportsExportRouteImport } from './routes/_app.reports.export'
import { Route as AppReportsExpensesRouteImport } from './routes/_app.reports.expenses'
import { Route as AppMaintenanceScheduleRouteImport } from './routes/_app.maintenance.schedule'
import { Route as AppMaintenanceNewRouteImport } from './routes/_app.maintenance.new'
import { Route as AppMaintenanceMaintenanceIdRouteImport } from './routes/_app.maintenance.$maintenanceId'
import { Route as AppFuelNewRouteImport } from './routes/_app.fuel.new'
import { Route as AppFuelHistoryRouteImport } from './routes/_app.fuel.history'
import { Route as AppFuelFuelLogIdRouteImport } from './routes/_app.fuel.$fuelLogId'
import { Route as AppExpensesNewRouteImport } from './routes/_app.expenses.new'
import { Route as AppExpensesHistoryRouteImport } from './routes/_app.expenses.history'
import { Route as AppExpensesExpenseIdRouteImport } from './routes/_app.expenses.$expenseId'
import { Route as AppDriversNewRouteImport } from './routes/_app.drivers.new'
import { Route as AppDriversDriverIdRouteImport } from './routes/_app.drivers.$driverId'
import { Route as AppVehiclesVehicleIdEditRouteImport } from './routes/_app.vehicles.$vehicleId.edit'
import { Route as AppVehiclesVehicleIdDocumentsRouteImport } from './routes/_app.vehicles.$vehicleId.documents'
import { Route as AppTripsTripIdEditRouteImport } from './routes/_app.trips.$tripId.edit'
import { Route as AppTripsTripIdDispatchRouteImport } from './routes/_app.trips.$tripId.dispatch'
import { Route as AppTripsTripIdCompleteRouteImport } from './routes/_app.trips.$tripId.complete'
import { Route as AppMaintenanceMaintenanceIdEditRouteImport } from './routes/_app.maintenance.$maintenanceId.edit'
import { Route as AppDriversDriverIdLicensesRouteImport } from './routes/_app.drivers.$driverId.licenses'
import { Route as AppDriversDriverIdEditRouteImport } from './routes/_app.drivers.$driverId.edit'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppFuelRoute = AppFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCopilotRoute = AppAiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesIndexRoute = AppVehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppTripsIndexRoute = AppTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppMaintenanceIndexRoute = AppMaintenanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMaintenanceRoute,
} as any)
const AppFuelIndexRoute = AppFuelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFuelRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppDriversIndexRoute = AppDriversIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDriversRoute,
} as any)
const AppVehiclesNewRoute = AppVehiclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppVehiclesVehicleIdRoute = AppVehiclesVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppTripsNewRoute = AppTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsHistoryRoute = AppTripsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdRoute = AppTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReportsRoiRoute = AppReportsRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsFuelRoute = AppReportsFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsFleetRoute = AppReportsFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsExportRoute = AppReportsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsExpensesRoute = AppReportsExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppMaintenanceScheduleRoute = AppMaintenanceScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppMaintenanceRoute,
} as any)
const AppMaintenanceNewRoute = AppMaintenanceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMaintenanceRoute,
} as any)
const AppMaintenanceMaintenanceIdRoute =
  AppMaintenanceMaintenanceIdRouteImport.update({
    id: '/$maintenanceId',
    path: '/$maintenanceId',
    getParentRoute: () => AppMaintenanceRoute,
  } as any)
const AppFuelNewRoute = AppFuelNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppFuelRoute,
} as any)
const AppFuelHistoryRoute = AppFuelHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppFuelRoute,
} as any)
const AppFuelFuelLogIdRoute = AppFuelFuelLogIdRouteImport.update({
  id: '/$fuelLogId',
  path: '/$fuelLogId',
  getParentRoute: () => AppFuelRoute,
} as any)
const AppExpensesNewRoute = AppExpensesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppExpensesHistoryRoute = AppExpensesHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppExpensesExpenseIdRoute = AppExpensesExpenseIdRouteImport.update({
  id: '/$expenseId',
  path: '/$expenseId',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppDriversNewRoute = AppDriversNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDriversRoute,
} as any)
const AppDriversDriverIdRoute = AppDriversDriverIdRouteImport.update({
  id: '/$driverId',
  path: '/$driverId',
  getParentRoute: () => AppDriversRoute,
} as any)
const AppVehiclesVehicleIdEditRoute =
  AppVehiclesVehicleIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppVehiclesVehicleIdRoute,
  } as any)
const AppVehiclesVehicleIdDocumentsRoute =
  AppVehiclesVehicleIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppVehiclesVehicleIdRoute,
  } as any)
const AppTripsTripIdEditRoute = AppTripsTripIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppTripsTripIdDispatchRoute = AppTripsTripIdDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppTripsTripIdCompleteRoute = AppTripsTripIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppMaintenanceMaintenanceIdEditRoute =
  AppMaintenanceMaintenanceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppMaintenanceMaintenanceIdRoute,
  } as any)
const AppDriversDriverIdLicensesRoute =
  AppDriversDriverIdLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AppDriversDriverIdRoute,
  } as any)
const AppDriversDriverIdEditRoute = AppDriversDriverIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppDriversDriverIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AppAiCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/drivers': typeof AppDriversRouteWithChildren
  '/expenses': typeof AppExpensesRouteWithChildren
  '/fuel': typeof AppFuelRouteWithChildren
  '/maintenance': typeof AppMaintenanceRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/trips': typeof AppTripsRouteWithChildren
  '/vehicles': typeof AppVehiclesRouteWithChildren
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/drivers/$driverId': typeof AppDriversDriverIdRouteWithChildren
  '/drivers/new': typeof AppDriversNewRoute
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/expenses/history': typeof AppExpensesHistoryRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/fuel/$fuelLogId': typeof AppFuelFuelLogIdRoute
  '/fuel/history': typeof AppFuelHistoryRoute
  '/fuel/new': typeof AppFuelNewRoute
  '/maintenance/$maintenanceId': typeof AppMaintenanceMaintenanceIdRouteWithChildren
  '/maintenance/new': typeof AppMaintenanceNewRoute
  '/maintenance/schedule': typeof AppMaintenanceScheduleRoute
  '/reports/expenses': typeof AppReportsExpensesRoute
  '/reports/export': typeof AppReportsExportRoute
  '/reports/fleet': typeof AppReportsFleetRoute
  '/reports/fuel': typeof AppReportsFuelRoute
  '/reports/roi': typeof AppReportsRoiRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/history': typeof AppTripsHistoryRoute
  '/trips/new': typeof AppTripsNewRoute
  '/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRouteWithChildren
  '/vehicles/new': typeof AppVehiclesNewRoute
  '/drivers/': typeof AppDriversIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/fuel/': typeof AppFuelIndexRoute
  '/maintenance/': typeof AppMaintenanceIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/trips/': typeof AppTripsIndexRoute
  '/vehicles/': typeof AppVehiclesIndexRoute
  '/drivers/$driverId/edit': typeof AppDriversDriverIdEditRoute
  '/drivers/$driverId/licenses': typeof AppDriversDriverIdLicensesRoute
  '/maintenance/$maintenanceId/edit': typeof AppMaintenanceMaintenanceIdEditRoute
  '/trips/$tripId/complete': typeof AppTripsTripIdCompleteRoute
  '/trips/$tripId/dispatch': typeof AppTripsTripIdDispatchRoute
  '/trips/$tripId/edit': typeof AppTripsTripIdEditRoute
  '/vehicles/$vehicleId/documents': typeof AppVehiclesVehicleIdDocumentsRoute
  '/vehicles/$vehicleId/edit': typeof AppVehiclesVehicleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AppAiCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/drivers/$driverId': typeof AppDriversDriverIdRouteWithChildren
  '/drivers/new': typeof AppDriversNewRoute
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/expenses/history': typeof AppExpensesHistoryRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/fuel/$fuelLogId': typeof AppFuelFuelLogIdRoute
  '/fuel/history': typeof AppFuelHistoryRoute
  '/fuel/new': typeof AppFuelNewRoute
  '/maintenance/$maintenanceId': typeof AppMaintenanceMaintenanceIdRouteWithChildren
  '/maintenance/new': typeof AppMaintenanceNewRoute
  '/maintenance/schedule': typeof AppMaintenanceScheduleRoute
  '/reports/expenses': typeof AppReportsExpensesRoute
  '/reports/export': typeof AppReportsExportRoute
  '/reports/fleet': typeof AppReportsFleetRoute
  '/reports/fuel': typeof AppReportsFuelRoute
  '/reports/roi': typeof AppReportsRoiRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/history': typeof AppTripsHistoryRoute
  '/trips/new': typeof AppTripsNewRoute
  '/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRouteWithChildren
  '/vehicles/new': typeof AppVehiclesNewRoute
  '/drivers': typeof AppDriversIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/fuel': typeof AppFuelIndexRoute
  '/maintenance': typeof AppMaintenanceIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/trips': typeof AppTripsIndexRoute
  '/vehicles': typeof AppVehiclesIndexRoute
  '/drivers/$driverId/edit': typeof AppDriversDriverIdEditRoute
  '/drivers/$driverId/licenses': typeof AppDriversDriverIdLicensesRoute
  '/maintenance/$maintenanceId/edit': typeof AppMaintenanceMaintenanceIdEditRoute
  '/trips/$tripId/complete': typeof AppTripsTripIdCompleteRoute
  '/trips/$tripId/dispatch': typeof AppTripsTripIdDispatchRoute
  '/trips/$tripId/edit': typeof AppTripsTripIdEditRoute
  '/vehicles/$vehicleId/documents': typeof AppVehiclesVehicleIdDocumentsRoute
  '/vehicles/$vehicleId/edit': typeof AppVehiclesVehicleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/ai-copilot': typeof AppAiCopilotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/drivers': typeof AppDriversRouteWithChildren
  '/_app/expenses': typeof AppExpensesRouteWithChildren
  '/_app/fuel': typeof AppFuelRouteWithChildren
  '/_app/maintenance': typeof AppMaintenanceRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/_app/vehicles': typeof AppVehiclesRouteWithChildren
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_app/drivers/$driverId': typeof AppDriversDriverIdRouteWithChildren
  '/_app/drivers/new': typeof AppDriversNewRoute
  '/_app/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/_app/expenses/history': typeof AppExpensesHistoryRoute
  '/_app/expenses/new': typeof AppExpensesNewRoute
  '/_app/fuel/$fuelLogId': typeof AppFuelFuelLogIdRoute
  '/_app/fuel/history': typeof AppFuelHistoryRoute
  '/_app/fuel/new': typeof AppFuelNewRoute
  '/_app/maintenance/$maintenanceId': typeof AppMaintenanceMaintenanceIdRouteWithChildren
  '/_app/maintenance/new': typeof AppMaintenanceNewRoute
  '/_app/maintenance/schedule': typeof AppMaintenanceScheduleRoute
  '/_app/reports/expenses': typeof AppReportsExpensesRoute
  '/_app/reports/export': typeof AppReportsExportRoute
  '/_app/reports/fleet': typeof AppReportsFleetRoute
  '/_app/reports/fuel': typeof AppReportsFuelRoute
  '/_app/reports/roi': typeof AppReportsRoiRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/_app/trips/history': typeof AppTripsHistoryRoute
  '/_app/trips/new': typeof AppTripsNewRoute
  '/_app/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRouteWithChildren
  '/_app/vehicles/new': typeof AppVehiclesNewRoute
  '/_app/drivers/': typeof AppDriversIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/fuel/': typeof AppFuelIndexRoute
  '/_app/maintenance/': typeof AppMaintenanceIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/trips/': typeof AppTripsIndexRoute
  '/_app/vehicles/': typeof AppVehiclesIndexRoute
  '/_app/drivers/$driverId/edit': typeof AppDriversDriverIdEditRoute
  '/_app/drivers/$driverId/licenses': typeof AppDriversDriverIdLicensesRoute
  '/_app/maintenance/$maintenanceId/edit': typeof AppMaintenanceMaintenanceIdEditRoute
  '/_app/trips/$tripId/complete': typeof AppTripsTripIdCompleteRoute
  '/_app/trips/$tripId/dispatch': typeof AppTripsTripIdDispatchRoute
  '/_app/trips/$tripId/edit': typeof AppTripsTripIdEditRoute
  '/_app/vehicles/$vehicleId/documents': typeof AppVehiclesVehicleIdDocumentsRoute
  '/_app/vehicles/$vehicleId/edit': typeof AppVehiclesVehicleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-copilot'
    | '/dashboard'
    | '/drivers'
    | '/expenses'
    | '/fuel'
    | '/maintenance'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/trips'
    | '/vehicles'
    | '/forgot-password'
    | '/login'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/expenses/$expenseId'
    | '/expenses/history'
    | '/expenses/new'
    | '/fuel/$fuelLogId'
    | '/fuel/history'
    | '/fuel/new'
    | '/maintenance/$maintenanceId'
    | '/maintenance/new'
    | '/maintenance/schedule'
    | '/reports/expenses'
    | '/reports/export'
    | '/reports/fleet'
    | '/reports/fuel'
    | '/reports/roi'
    | '/settings/account'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/security'
    | '/trips/$tripId'
    | '/trips/history'
    | '/trips/new'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
    | '/drivers/'
    | '/expenses/'
    | '/fuel/'
    | '/maintenance/'
    | '/reports/'
    | '/settings/'
    | '/trips/'
    | '/vehicles/'
    | '/drivers/$driverId/edit'
    | '/drivers/$driverId/licenses'
    | '/maintenance/$maintenanceId/edit'
    | '/trips/$tripId/complete'
    | '/trips/$tripId/dispatch'
    | '/trips/$tripId/edit'
    | '/vehicles/$vehicleId/documents'
    | '/vehicles/$vehicleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-copilot'
    | '/dashboard'
    | '/notifications'
    | '/forgot-password'
    | '/login'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/expenses/$expenseId'
    | '/expenses/history'
    | '/expenses/new'
    | '/fuel/$fuelLogId'
    | '/fuel/history'
    | '/fuel/new'
    | '/maintenance/$maintenanceId'
    | '/maintenance/new'
    | '/maintenance/schedule'
    | '/reports/expenses'
    | '/reports/export'
    | '/reports/fleet'
    | '/reports/fuel'
    | '/reports/roi'
    | '/settings/account'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/security'
    | '/trips/$tripId'
    | '/trips/history'
    | '/trips/new'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
    | '/drivers'
    | '/expenses'
    | '/fuel'
    | '/maintenance'
    | '/reports'
    | '/settings'
    | '/trips'
    | '/vehicles'
    | '/drivers/$driverId/edit'
    | '/drivers/$driverId/licenses'
    | '/maintenance/$maintenanceId/edit'
    | '/trips/$tripId/complete'
    | '/trips/$tripId/dispatch'
    | '/trips/$tripId/edit'
    | '/vehicles/$vehicleId/documents'
    | '/vehicles/$vehicleId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_public'
    | '/_app/ai-copilot'
    | '/_app/dashboard'
    | '/_app/drivers'
    | '/_app/expenses'
    | '/_app/fuel'
    | '/_app/maintenance'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/trips'
    | '/_app/vehicles'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_app/drivers/$driverId'
    | '/_app/drivers/new'
    | '/_app/expenses/$expenseId'
    | '/_app/expenses/history'
    | '/_app/expenses/new'
    | '/_app/fuel/$fuelLogId'
    | '/_app/fuel/history'
    | '/_app/fuel/new'
    | '/_app/maintenance/$maintenanceId'
    | '/_app/maintenance/new'
    | '/_app/maintenance/schedule'
    | '/_app/reports/expenses'
    | '/_app/reports/export'
    | '/_app/reports/fleet'
    | '/_app/reports/fuel'
    | '/_app/reports/roi'
    | '/_app/settings/account'
    | '/_app/settings/preferences'
    | '/_app/settings/profile'
    | '/_app/settings/roles'
    | '/_app/settings/security'
    | '/_app/trips/$tripId'
    | '/_app/trips/history'
    | '/_app/trips/new'
    | '/_app/vehicles/$vehicleId'
    | '/_app/vehicles/new'
    | '/_app/drivers/'
    | '/_app/expenses/'
    | '/_app/fuel/'
    | '/_app/maintenance/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/trips/'
    | '/_app/vehicles/'
    | '/_app/drivers/$driverId/edit'
    | '/_app/drivers/$driverId/licenses'
    | '/_app/maintenance/$maintenanceId/edit'
    | '/_app/trips/$tripId/complete'
    | '/_app/trips/$tripId/dispatch'
    | '/_app/trips/$tripId/edit'
    | '/_app/vehicles/$vehicleId/documents'
    | '/_app/vehicles/$vehicleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fuel': {
      id: '/_app/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof AppFuelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers': {
      id: '/_app/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-copilot': {
      id: '/_app/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AppAiCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles/': {
      id: '/_app/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AppVehiclesIndexRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/trips/': {
      id: '/_app/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof AppTripsIndexRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/maintenance/': {
      id: '/_app/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AppMaintenanceIndexRouteImport
      parentRoute: typeof AppMaintenanceRoute
    }
    '/_app/fuel/': {
      id: '/_app/fuel/'
      path: '/'
      fullPath: '/fuel/'
      preLoaderRoute: typeof AppFuelIndexRouteImport
      parentRoute: typeof AppFuelRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/drivers/': {
      id: '/_app/drivers/'
      path: '/'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AppDriversIndexRouteImport
      parentRoute: typeof AppDriversRoute
    }
    '/_app/vehicles/new': {
      id: '/_app/vehicles/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof AppVehiclesNewRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/vehicles/$vehicleId': {
      id: '/_app/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AppVehiclesVehicleIdRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/trips/new': {
      id: '/_app/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AppTripsNewRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/history': {
      id: '/_app/trips/history'
      path: '/history'
      fullPath: '/trips/history'
      preLoaderRoute: typeof AppTripsHistoryRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId': {
      id: '/_app/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AppTripsTripIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/reports/roi': {
      id: '/_app/reports/roi'
      path: '/roi'
      fullPath: '/reports/roi'
      preLoaderRoute: typeof AppReportsRoiRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/fuel': {
      id: '/_app/reports/fuel'
      path: '/fuel'
      fullPath: '/reports/fuel'
      preLoaderRoute: typeof AppReportsFuelRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/fleet': {
      id: '/_app/reports/fleet'
      path: '/fleet'
      fullPath: '/reports/fleet'
      preLoaderRoute: typeof AppReportsFleetRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/export': {
      id: '/_app/reports/export'
      path: '/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof AppReportsExportRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/expenses': {
      id: '/_app/reports/expenses'
      path: '/expenses'
      fullPath: '/reports/expenses'
      preLoaderRoute: typeof AppReportsExpensesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/maintenance/schedule': {
      id: '/_app/maintenance/schedule'
      path: '/schedule'
      fullPath: '/maintenance/schedule'
      preLoaderRoute: typeof AppMaintenanceScheduleRouteImport
      parentRoute: typeof AppMaintenanceRoute
    }
    '/_app/maintenance/new': {
      id: '/_app/maintenance/new'
      path: '/new'
      fullPath: '/maintenance/new'
      preLoaderRoute: typeof AppMaintenanceNewRouteImport
      parentRoute: typeof AppMaintenanceRoute
    }
    '/_app/maintenance/$maintenanceId': {
      id: '/_app/maintenance/$maintenanceId'
      path: '/$maintenanceId'
      fullPath: '/maintenance/$maintenanceId'
      preLoaderRoute: typeof AppMaintenanceMaintenanceIdRouteImport
      parentRoute: typeof AppMaintenanceRoute
    }
    '/_app/fuel/new': {
      id: '/_app/fuel/new'
      path: '/new'
      fullPath: '/fuel/new'
      preLoaderRoute: typeof AppFuelNewRouteImport
      parentRoute: typeof AppFuelRoute
    }
    '/_app/fuel/history': {
      id: '/_app/fuel/history'
      path: '/history'
      fullPath: '/fuel/history'
      preLoaderRoute: typeof AppFuelHistoryRouteImport
      parentRoute: typeof AppFuelRoute
    }
    '/_app/fuel/$fuelLogId': {
      id: '/_app/fuel/$fuelLogId'
      path: '/$fuelLogId'
      fullPath: '/fuel/$fuelLogId'
      preLoaderRoute: typeof AppFuelFuelLogIdRouteImport
      parentRoute: typeof AppFuelRoute
    }
    '/_app/expenses/new': {
      id: '/_app/expenses/new'
      path: '/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AppExpensesNewRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/expenses/history': {
      id: '/_app/expenses/history'
      path: '/history'
      fullPath: '/expenses/history'
      preLoaderRoute: typeof AppExpensesHistoryRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/expenses/$expenseId': {
      id: '/_app/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AppExpensesExpenseIdRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/drivers/new': {
      id: '/_app/drivers/new'
      path: '/new'
      fullPath: '/drivers/new'
      preLoaderRoute: typeof AppDriversNewRouteImport
      parentRoute: typeof AppDriversRoute
    }
    '/_app/drivers/$driverId': {
      id: '/_app/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof AppDriversDriverIdRouteImport
      parentRoute: typeof AppDriversRoute
    }
    '/_app/vehicles/$vehicleId/edit': {
      id: '/_app/vehicles/$vehicleId/edit'
      path: '/edit'
      fullPath: '/vehicles/$vehicleId/edit'
      preLoaderRoute: typeof AppVehiclesVehicleIdEditRouteImport
      parentRoute: typeof AppVehiclesVehicleIdRoute
    }
    '/_app/vehicles/$vehicleId/documents': {
      id: '/_app/vehicles/$vehicleId/documents'
      path: '/documents'
      fullPath: '/vehicles/$vehicleId/documents'
      preLoaderRoute: typeof AppVehiclesVehicleIdDocumentsRouteImport
      parentRoute: typeof AppVehiclesVehicleIdRoute
    }
    '/_app/trips/$tripId/edit': {
      id: '/_app/trips/$tripId/edit'
      path: '/edit'
      fullPath: '/trips/$tripId/edit'
      preLoaderRoute: typeof AppTripsTripIdEditRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/trips/$tripId/dispatch': {
      id: '/_app/trips/$tripId/dispatch'
      path: '/dispatch'
      fullPath: '/trips/$tripId/dispatch'
      preLoaderRoute: typeof AppTripsTripIdDispatchRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/trips/$tripId/complete': {
      id: '/_app/trips/$tripId/complete'
      path: '/complete'
      fullPath: '/trips/$tripId/complete'
      preLoaderRoute: typeof AppTripsTripIdCompleteRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/maintenance/$maintenanceId/edit': {
      id: '/_app/maintenance/$maintenanceId/edit'
      path: '/edit'
      fullPath: '/maintenance/$maintenanceId/edit'
      preLoaderRoute: typeof AppMaintenanceMaintenanceIdEditRouteImport
      parentRoute: typeof AppMaintenanceMaintenanceIdRoute
    }
    '/_app/drivers/$driverId/licenses': {
      id: '/_app/drivers/$driverId/licenses'
      path: '/licenses'
      fullPath: '/drivers/$driverId/licenses'
      preLoaderRoute: typeof AppDriversDriverIdLicensesRouteImport
      parentRoute: typeof AppDriversDriverIdRoute
    }
    '/_app/drivers/$driverId/edit': {
      id: '/_app/drivers/$driverId/edit'
      path: '/edit'
      fullPath: '/drivers/$driverId/edit'
      preLoaderRoute: typeof AppDriversDriverIdEditRouteImport
      parentRoute: typeof AppDriversDriverIdRoute
    }
  }
}

interface AppDriversDriverIdRouteChildren {
  AppDriversDriverIdEditRoute: typeof AppDriversDriverIdEditRoute
  AppDriversDriverIdLicensesRoute: typeof AppDriversDriverIdLicensesRoute
}

const AppDriversDriverIdRouteChildren: AppDriversDriverIdRouteChildren = {
  AppDriversDriverIdEditRoute: AppDriversDriverIdEditRoute,
  AppDriversDriverIdLicensesRoute: AppDriversDriverIdLicensesRoute,
}

const AppDriversDriverIdRouteWithChildren =
  AppDriversDriverIdRoute._addFileChildren(AppDriversDriverIdRouteChildren)

interface AppDriversRouteChildren {
  AppDriversDriverIdRoute: typeof AppDriversDriverIdRouteWithChildren
  AppDriversNewRoute: typeof AppDriversNewRoute
  AppDriversIndexRoute: typeof AppDriversIndexRoute
}

const AppDriversRouteChildren: AppDriversRouteChildren = {
  AppDriversDriverIdRoute: AppDriversDriverIdRouteWithChildren,
  AppDriversNewRoute: AppDriversNewRoute,
  AppDriversIndexRoute: AppDriversIndexRoute,
}

const AppDriversRouteWithChildren = AppDriversRoute._addFileChildren(
  AppDriversRouteChildren,
)

interface AppExpensesRouteChildren {
  AppExpensesExpenseIdRoute: typeof AppExpensesExpenseIdRoute
  AppExpensesHistoryRoute: typeof AppExpensesHistoryRoute
  AppExpensesNewRoute: typeof AppExpensesNewRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppExpensesRouteChildren: AppExpensesRouteChildren = {
  AppExpensesExpenseIdRoute: AppExpensesExpenseIdRoute,
  AppExpensesHistoryRoute: AppExpensesHistoryRoute,
  AppExpensesNewRoute: AppExpensesNewRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppExpensesRouteWithChildren = AppExpensesRoute._addFileChildren(
  AppExpensesRouteChildren,
)

interface AppFuelRouteChildren {
  AppFuelFuelLogIdRoute: typeof AppFuelFuelLogIdRoute
  AppFuelHistoryRoute: typeof AppFuelHistoryRoute
  AppFuelNewRoute: typeof AppFuelNewRoute
  AppFuelIndexRoute: typeof AppFuelIndexRoute
}

const AppFuelRouteChildren: AppFuelRouteChildren = {
  AppFuelFuelLogIdRoute: AppFuelFuelLogIdRoute,
  AppFuelHistoryRoute: AppFuelHistoryRoute,
  AppFuelNewRoute: AppFuelNewRoute,
  AppFuelIndexRoute: AppFuelIndexRoute,
}

const AppFuelRouteWithChildren =
  AppFuelRoute._addFileChildren(AppFuelRouteChildren)

interface AppMaintenanceMaintenanceIdRouteChildren {
  AppMaintenanceMaintenanceIdEditRoute: typeof AppMaintenanceMaintenanceIdEditRoute
}

const AppMaintenanceMaintenanceIdRouteChildren: AppMaintenanceMaintenanceIdRouteChildren =
  {
    AppMaintenanceMaintenanceIdEditRoute: AppMaintenanceMaintenanceIdEditRoute,
  }

const AppMaintenanceMaintenanceIdRouteWithChildren =
  AppMaintenanceMaintenanceIdRoute._addFileChildren(
    AppMaintenanceMaintenanceIdRouteChildren,
  )

interface AppMaintenanceRouteChildren {
  AppMaintenanceMaintenanceIdRoute: typeof AppMaintenanceMaintenanceIdRouteWithChildren
  AppMaintenanceNewRoute: typeof AppMaintenanceNewRoute
  AppMaintenanceScheduleRoute: typeof AppMaintenanceScheduleRoute
  AppMaintenanceIndexRoute: typeof AppMaintenanceIndexRoute
}

const AppMaintenanceRouteChildren: AppMaintenanceRouteChildren = {
  AppMaintenanceMaintenanceIdRoute:
    AppMaintenanceMaintenanceIdRouteWithChildren,
  AppMaintenanceNewRoute: AppMaintenanceNewRoute,
  AppMaintenanceScheduleRoute: AppMaintenanceScheduleRoute,
  AppMaintenanceIndexRoute: AppMaintenanceIndexRoute,
}

const AppMaintenanceRouteWithChildren = AppMaintenanceRoute._addFileChildren(
  AppMaintenanceRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsExpensesRoute: typeof AppReportsExpensesRoute
  AppReportsExportRoute: typeof AppReportsExportRoute
  AppReportsFleetRoute: typeof AppReportsFleetRoute
  AppReportsFuelRoute: typeof AppReportsFuelRoute
  AppReportsRoiRoute: typeof AppReportsRoiRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsExpensesRoute: AppReportsExpensesRoute,
  AppReportsExportRoute: AppReportsExportRoute,
  AppReportsFleetRoute: AppReportsFleetRoute,
  AppReportsFuelRoute: AppReportsFuelRoute,
  AppReportsRoiRoute: AppReportsRoiRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTripsTripIdRouteChildren {
  AppTripsTripIdCompleteRoute: typeof AppTripsTripIdCompleteRoute
  AppTripsTripIdDispatchRoute: typeof AppTripsTripIdDispatchRoute
  AppTripsTripIdEditRoute: typeof AppTripsTripIdEditRoute
}

const AppTripsTripIdRouteChildren: AppTripsTripIdRouteChildren = {
  AppTripsTripIdCompleteRoute: AppTripsTripIdCompleteRoute,
  AppTripsTripIdDispatchRoute: AppTripsTripIdDispatchRoute,
  AppTripsTripIdEditRoute: AppTripsTripIdEditRoute,
}

const AppTripsTripIdRouteWithChildren = AppTripsTripIdRoute._addFileChildren(
  AppTripsTripIdRouteChildren,
)

interface AppTripsRouteChildren {
  AppTripsTripIdRoute: typeof AppTripsTripIdRouteWithChildren
  AppTripsHistoryRoute: typeof AppTripsHistoryRoute
  AppTripsNewRoute: typeof AppTripsNewRoute
  AppTripsIndexRoute: typeof AppTripsIndexRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsTripIdRoute: AppTripsTripIdRouteWithChildren,
  AppTripsHistoryRoute: AppTripsHistoryRoute,
  AppTripsNewRoute: AppTripsNewRoute,
  AppTripsIndexRoute: AppTripsIndexRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppVehiclesVehicleIdRouteChildren {
  AppVehiclesVehicleIdDocumentsRoute: typeof AppVehiclesVehicleIdDocumentsRoute
  AppVehiclesVehicleIdEditRoute: typeof AppVehiclesVehicleIdEditRoute
}

const AppVehiclesVehicleIdRouteChildren: AppVehiclesVehicleIdRouteChildren = {
  AppVehiclesVehicleIdDocumentsRoute: AppVehiclesVehicleIdDocumentsRoute,
  AppVehiclesVehicleIdEditRoute: AppVehiclesVehicleIdEditRoute,
}

const AppVehiclesVehicleIdRouteWithChildren =
  AppVehiclesVehicleIdRoute._addFileChildren(AppVehiclesVehicleIdRouteChildren)

interface AppVehiclesRouteChildren {
  AppVehiclesVehicleIdRoute: typeof AppVehiclesVehicleIdRouteWithChildren
  AppVehiclesNewRoute: typeof AppVehiclesNewRoute
  AppVehiclesIndexRoute: typeof AppVehiclesIndexRoute
}

const AppVehiclesRouteChildren: AppVehiclesRouteChildren = {
  AppVehiclesVehicleIdRoute: AppVehiclesVehicleIdRouteWithChildren,
  AppVehiclesNewRoute: AppVehiclesNewRoute,
  AppVehiclesIndexRoute: AppVehiclesIndexRoute,
}

const AppVehiclesRouteWithChildren = AppVehiclesRoute._addFileChildren(
  AppVehiclesRouteChildren,
)

interface AppRouteChildren {
  AppAiCopilotRoute: typeof AppAiCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDriversRoute: typeof AppDriversRouteWithChildren
  AppExpensesRoute: typeof AppExpensesRouteWithChildren
  AppFuelRoute: typeof AppFuelRouteWithChildren
  AppMaintenanceRoute: typeof AppMaintenanceRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTripsRoute: typeof AppTripsRouteWithChildren
  AppVehiclesRoute: typeof AppVehiclesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAiCopilotRoute: AppAiCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDriversRoute: AppDriversRouteWithChildren,
  AppExpensesRoute: AppExpensesRouteWithChildren,
  AppFuelRoute: AppFuelRouteWithChildren,
  AppMaintenanceRoute: AppMaintenanceRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTripsRoute: AppTripsRouteWithChildren,
  AppVehiclesRoute: AppVehiclesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
